// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StudentskiDom.Infrastructure.Data;

#nullable disable

namespace StudentskiDom.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260410214704_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("StudentskiDom.Domain.Entities.AccessLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessAction")
                        .HasColumnType("integer");

                    b.Property<Guid>("AccessRightId")
                        .HasColumnType("uuid");

                    b.Property<string>("Details")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AccessRightId");

                    b.HasIndex("UserId");

                    b.ToTable("AccessLogs");
                });

            modelBuilder.Entity("StudentskiDom.Domain.Entities.AccessRight", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessType")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("GrantedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GrantedByUserId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid?>("ResourceId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RoomId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GrantedByUserId");

                    b.HasIndex("ResourceId");

                    b.HasIndex("RoomId");

                    b.HasIndex("UserId");

                    b.ToTable("AccessRights");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f6666666-6666-6666-6666-666666666661"),
                            AccessType = 0,
                            ExpiresAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GrantedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GrantedByUserId = new Guid("a1111111-1111-1111-1111-111111111111"),
                            IsActive = true,
                            Reason = "Smještaj za akademsku godinu 2025/26",
                            RoomId = new Guid("d4444444-4444-4444-4444-444444444441"),
                            UserId = new Guid("c3333333-3333-3333-3333-333333333333")
                        },
                        new
                        {
                            Id = new Guid("f6666666-6666-6666-6666-666666666662"),
                            AccessType = 1,
                            GrantedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GrantedByUserId = new Guid("a1111111-1111-1111-1111-111111111111"),
                            IsActive = true,
                            Reason = "Pristup kuhinji",
                            ResourceId = new Guid("e5555555-5555-5555-5555-555555555551"),
                            UserId = new Guid("c3333333-3333-3333-3333-333333333333")
                        },
                        new
                        {
                            Id = new Guid("f6666666-6666-6666-6666-666666666663"),
                            AccessType = 2,
                            GrantedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GrantedByUserId = new Guid("a1111111-1111-1111-1111-111111111111"),
                            IsActive = true,
                            Reason = "Pristup WiFi mreži",
                            ResourceId = new Guid("e5555555-5555-5555-5555-555555555554"),
                            UserId = new Guid("c3333333-3333-3333-3333-333333333333")
                        });
                });

            modelBuilder.Entity("StudentskiDom.Domain.Entities.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuthorUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsInternal")
                        .HasColumnType("boolean");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AuthorUserId");

                    b.HasIndex("RequestId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-1111-2222-3333-444444444444"),
                            AuthorUserId = new Guid("b2222222-2222-2222-2222-222222222222"),
                            Content = "Pregled je zakazan za sutra u 10h.",
                            CreatedAt = new DateTime(2025, 11, 16, 8, 0, 0, 0, DateTimeKind.Utc),
                            IsInternal = false,
                            RequestId = new Guid("11111111-aaaa-bbbb-cccc-111111111111")
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-1111-2222-3333-444444444444"),
                            AuthorUserId = new Guid("a1111111-1111-1111-1111-111111111111"),
                            Content = "Trebamo naručiti novi radijator, stari je neispravan.",
                            CreatedAt = new DateTime(2025, 11, 16, 9, 0, 0, 0, DateTimeKind.Utc),
                            IsInternal = true,
                            RequestId = new Guid("11111111-aaaa-bbbb-cccc-111111111111")
                        },
                        new
                        {
                            Id = new Guid("cccccccc-1111-2222-3333-444444444444"),
                            AuthorUserId = new Guid("a1111111-1111-1111-1111-111111111111"),
                            Content = "Potvrda je izdana. Možete je preuzeti u kancelariji.",
                            CreatedAt = new DateTime(2025, 10, 7, 11, 0, 0, 0, DateTimeKind.Utc),
                            IsInternal = false,
                            RequestId = new Guid("33333333-aaaa-bbbb-cccc-333333333333")
                        });
                });

            modelBuilder.Entity("StudentskiDom.Domain.Entities.Request", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssignedToUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<int>("RequestType")
                        .HasColumnType("integer");

                    b.Property<Guid>("RequestedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("RoomId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AssignedToUserId");

                    b.HasIndex("RequestedByUserId");

                    b.HasIndex("RoomId");

                    b.ToTable("Requests");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-aaaa-bbbb-cccc-111111111111"),
                            AssignedToUserId = new Guid("b2222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2025, 11, 15, 10, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Radijator ne grije, molim hitnu intervenciju jer je hladno.",
                            Priority = 2,
                            RequestType = 0,
                            RequestedByUserId = new Guid("c3333333-3333-3333-3333-333333333333"),
                            RoomId = new Guid("d4444444-4444-4444-4444-444444444441"),
                            Status = 1,
                            Title = "Pokvaren radijator u sobi A-101",
                            UpdatedAt = new DateTime(2025, 11, 16, 8, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("22222222-aaaa-bbbb-cccc-222222222222"),
                            CreatedAt = new DateTime(2025, 12, 1, 14, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Stolica u sobi je slomljena, potrebna zamjena.",
                            Priority = 1,
                            RequestType = 1,
                            RequestedByUserId = new Guid("c3333333-3333-3333-3333-333333333333"),
                            RoomId = new Guid("d4444444-4444-4444-4444-444444444441"),
                            Status = 0,
                            Title = "Zamjena stolice",
                            UpdatedAt = new DateTime(2025, 12, 1, 14, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("33333333-aaaa-bbbb-cccc-333333333333"),
                            AssignedToUserId = new Guid("a1111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2025, 10, 5, 9, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Trebam potvrdu o boravku za fakultet.",
                            Priority = 0,
                            RequestType = 2,
                            RequestedByUserId = new Guid("c3333333-3333-3333-3333-333333333333"),
                            ResolvedAt = new DateTime(2025, 10, 7, 11, 0, 0, 0, DateTimeKind.Utc),
                            Status = 2,
                            Title = "Potvrda o boravku",
                            UpdatedAt = new DateTime(2025, 10, 7, 11, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("StudentskiDom.Domain.Entities.Resource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("ResourceType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Resources");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e5555555-5555-5555-5555-555555555551"),
                            Description = "Zajednička kuhinja na prvom spratu",
                            IsActive = true,
                            Location = "Paviljon A, 1. sprat",
                            Name = "Kuhinja - Paviljon A",
                            ResourceType = 1
                        },
                        new
                        {
                            Id = new Guid("e5555555-5555-5555-5555-555555555552"),
                            Description = "Fitness centar za studente",
                            IsActive = true,
                            Location = "Paviljon B, prizemlje",
                            Name = "Teretana",
                            ResourceType = 2
                        },
                        new
                        {
                            Id = new Guid("e5555555-5555-5555-5555-555555555553"),
                            Description = "Učionica za grupno učenje",
                            IsActive = true,
                            Location = "Paviljon A, 3. sprat",
                            Name = "Učionica 1",
                            ResourceType = 3
                        },
                        new
                        {
                            Id = new Guid("e5555555-5555-5555-5555-555555555554"),
                            Description = "Pristup internet mreži u domu",
                            IsActive = true,
                            Location = "Cijeli dom",
                            Name = "WiFi Mreža",
                            ResourceType = 5
                        });
                });

            modelBuilder.Entity("StudentskiDom.Domain.Entities.Room", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Building")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<int>("Floor")
                        .HasColumnType("integer");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean");

                    b.Property<string>("RoomNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("RoomType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RoomNumber")
                        .IsUnique();

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d4444444-4444-4444-4444-444444444441"),
                            Building = "Paviljon A",
                            Capacity = 2,
                            Floor = 1,
                            IsAvailable = true,
                            RoomNumber = "A-101",
                            RoomType = 1
                        },
                        new
                        {
                            Id = new Guid("d4444444-4444-4444-4444-444444444442"),
                            Building = "Paviljon A",
                            Capacity = 2,
                            Floor = 1,
                            IsAvailable = true,
                            RoomNumber = "A-102",
                            RoomType = 1
                        },
                        new
                        {
                            Id = new Guid("d4444444-4444-4444-4444-444444444443"),
                            Building = "Paviljon A",
                            Capacity = 1,
                            Floor = 2,
                            IsAvailable = false,
                            RoomNumber = "A-201",
                            RoomType = 0
                        },
                        new
                        {
                            Id = new Guid("d4444444-4444-4444-4444-444444444444"),
                            Building = "Paviljon B",
                            Capacity = 3,
                            Floor = 1,
                            IsAvailable = true,
                            RoomNumber = "B-101",
                            RoomType = 2
                        },
                        new
                        {
                            Id = new Guid("d4444444-4444-4444-4444-444444444445"),
                            Building = "Paviljon B",
                            Capacity = 2,
                            Floor = 2,
                            IsAvailable = true,
                            RoomNumber = "B-201",
                            RoomType = 1
                        });
                });

            modelBuilder.Entity("StudentskiDom.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<int>("StudentStatus")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@studentskidom.ba",
                            FirstName = "Admin",
                            LastName = "Adminović",
                            PasswordHash = "$2a$11$tIctmXJSmbowkf.lIjr2l.ru4slaMMT7yMXDiwu3kZIoWVVWNPyv.",
                            PhoneNumber = "+38761000001",
                            Role = 1,
                            StudentStatus = 0,
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("b2222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "staff@studentskidom.ba",
                            FirstName = "Tehničar",
                            LastName = "Tehničarević",
                            PasswordHash = "$2a$11$x2gNsrCKHCqawyfD0ZLtOug0Mt718Ot8UCSuc.Shx0JBSS.KKEPLW",
                            PhoneNumber = "+38761000002",
                            Role = 2,
                            StudentStatus = 0,
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("c3333333-3333-3333-3333-333333333333"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "student@studentskidom.ba",
                            FirstName = "Student",
                            LastName = "Studentović",
                            PasswordHash = "$2a$11$XZatqBSc46WICE9BVgY6YuDTm6q5mkTSK8DNBG.0sKCApqNwReYv.",
                            PhoneNumber = "+38761000003",
                            Role = 0,
                            StudentStatus = 0,
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("StudentskiDom.Domain.Entities.AccessLog", b =>
                {
                    b.HasOne("StudentskiDom.Domain.Entities.AccessRight", "AccessRight")
                        .WithMany("AccessLogs")
                        .HasForeignKey("AccessRightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentskiDom.Domain.Entities.User", "User")
                        .WithMany("AccessLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccessRight");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StudentskiDom.Domain.Entities.AccessRight", b =>
                {
                    b.HasOne("StudentskiDom.Domain.Entities.User", "GrantedByUser")
                        .WithMany("GrantedAccessRights")
                        .HasForeignKey("GrantedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StudentskiDom.Domain.Entities.Resource", "Resource")
                        .WithMany("AccessRights")
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("StudentskiDom.Domain.Entities.Room", "Room")
                        .WithMany("AccessRights")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("StudentskiDom.Domain.Entities.User", "User")
                        .WithMany("AccessRights")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GrantedByUser");

                    b.Navigation("Resource");

                    b.Navigation("Room");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StudentskiDom.Domain.Entities.Comment", b =>
                {
                    b.HasOne("StudentskiDom.Domain.Entities.User", "AuthorUser")
                        .WithMany("Comments")
                        .HasForeignKey("AuthorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StudentskiDom.Domain.Entities.Request", "Request")
                        .WithMany("Comments")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AuthorUser");

                    b.Navigation("Request");
                });

            modelBuilder.Entity("StudentskiDom.Domain.Entities.Request", b =>
                {
                    b.HasOne("StudentskiDom.Domain.Entities.User", "AssignedToUser")
                        .WithMany("AssignedRequests")
                        .HasForeignKey("AssignedToUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("StudentskiDom.Domain.Entities.User", "RequestedByUser")
                        .WithMany("SubmittedRequests")
                        .HasForeignKey("RequestedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentskiDom.Domain.Entities.Room", "Room")
                        .WithMany("Requests")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AssignedToUser");

                    b.Navigation("RequestedByUser");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("StudentskiDom.Domain.Entities.AccessRight", b =>
                {
                    b.Navigation("AccessLogs");
                });

            modelBuilder.Entity("StudentskiDom.Domain.Entities.Request", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("StudentskiDom.Domain.Entities.Resource", b =>
                {
                    b.Navigation("AccessRights");
                });

            modelBuilder.Entity("StudentskiDom.Domain.Entities.Room", b =>
                {
                    b.Navigation("AccessRights");

                    b.Navigation("Requests");
                });

            modelBuilder.Entity("StudentskiDom.Domain.Entities.User", b =>
                {
                    b.Navigation("AccessLogs");

                    b.Navigation("AccessRights");

                    b.Navigation("AssignedRequests");

                    b.Navigation("Comments");

                    b.Navigation("GrantedAccessRights");

                    b.Navigation("SubmittedRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
